name: Xcode - Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Detect Scheme and Project
        id: detect
        run: |
          project_file=$(find . -name "*.xcodeproj" | head -n 1)
          scheme=$(xcodebuild -list -project "$project_file" -json | ruby -rjson -e 'puts JSON.parse(STDIN.read)["project"]["targets"][0]')
          echo "project_file=$project_file" >> $GITHUB_OUTPUT
          echo "scheme=$scheme" >> $GITHUB_OUTPUT

      - name: Build and Test
        run: |
          xcodebuild clean build test \
            -project "${{ steps.detect.outputs.project_file }}" \
            -scheme "${{ steps.detect.outputs.scheme }}" \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.4" \
            | xcpretty
